"""
Django settings for recommendica project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent


def load_project_env():
    """
    Load the environment file that matches the current mode.

    Development is the default for local commands. Production is selected
    when DEVELOPMENT_MODE is explicitly false, which is how docker compose
    and the deploy target run.
    """

    development_mode = os.getenv("DEVELOPMENT_MODE", "True").lower() == "true"
    env_file = ".env.development" if development_mode else ".env.production"
    load_dotenv(BASE_DIR / env_file, override=False)


load_project_env()

for env_name in (
    "OPENAI_API_KEY",
    "LANGSMITH_ENDPOINT",
    "LANGSMITH_API_KEY",
    "LANGSMITH_PROJECT",
):
    env_value = os.getenv(env_name)
    if env_value is not None:
        os.environ[env_name] = env_value
    

CHROMA_HOST = os.getenv("RE_CHROMA_HOST", "localhost")
CHROMA_PORT = int(os.getenv("RE_CHROMA_PORT", "8040"))

os.environ["LANGSMITH_TRACING"] = os.getenv("LANGSMITH_TRACING", "True")

SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")

DEFAULT_LLM_MODEL = os.getenv("DEFAULT_LLM_MODEL", "google/gemma-4-26b-a4b-it")

# ── AI / RAG Pipeline Settings ─────────────────────────────────────────────

# Embedding
OLLAMA_EMBEDDING_MODEL = os.getenv("OLLAMA_EMBEDDING_MODEL", "embeddinggemma")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "embeddinggemma")
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "100"))

# LLM
DENSE_LLM_MODEL = os.getenv("DENSE_LLM_MODEL", "google/gemma-4-26b-a4b-it")
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0"))

# Retrieval
TOP_K = int(os.getenv("TOP_K", "5"))
CANDIDATE_MULTIPLIER = int(os.getenv("CANDIDATE_MULTIPLIER", "4"))
CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "5"))
COLLECTION_NAME = os.getenv("COLLECTION_NAME", "arxiv_collection")

# Rerank (None = disabled)
RERANK_MODEL = os.getenv("RERANK_MODEL") or None
RERANK_TOP_N = os.getenv("RERANK_TOP_N") or None

# Query-transform models
HYDE_MODEL = os.getenv("HYDE_MODEL", "mistralai/mistral-nemo")
STEP_BACK_MODEL = os.getenv("STEP_BACK_MODEL","mistralai/mistral-nemo")
RAG_FUSION_MODEL = os.getenv("RAG_FUSION_MODEL", "mistralai/mistral-nemo")
RAG_FUSION_N_VARIANTS = int(os.getenv("RAG_FUSION_N_VARIANTS", "4"))

# Confidence gate
CONFIDENCE_ALPHA = float(os.getenv("CONFIDENCE_ALPHA", "0.5"))
CONFIDENCE_BETA = float(os.getenv("CONFIDENCE_BETA", "0.3"))
CONFIDENCE_GAMMA = float(os.getenv("CONFIDENCE_GAMMA", "0.2"))
CONFIDENCE_THRESHOLD = float(os.getenv("CONFIDENCE_THRESHOLD", "0.75"))

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "airecommender",
    "corsheaders",
]

REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Research Recommender API',
    'DESCRIPTION': 'Arxiv Research Recommender API with Advanced RAG pipeline',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "recommendica.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "recommendica.wsgi.application"


DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False").lower() == "true"

if not DEVELOPMENT_MODE:
    required_vars = [
        "DB_NAME",
        "DB_USER",
        "DB_PASSWORD",
        "DB_HOST",
    ]

    missing = [var for var in required_vars if not os.getenv(var)]

    if missing:
        raise Exception(
            f"Missing required database environment variables: {', '.join(missing)}"
        )

if DEVELOPMENT_MODE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "db"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
