# Generated by Django 5.2.15 on 2026-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airecommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_transaction_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('amount_minor', models.BigIntegerField(help_text='Amount in minor units (e.g. cents).')),
                ('currency', models.CharField(max_length=3)),
                ('email', models.EmailField(blank=True, help_text='Payer email, when Paddle sends one.', max_length=254)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('last_event_id', models.CharField(blank=True, max_length=64)),
                ('last_event_type', models.CharField(blank=True, max_length=64)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='airecommend_status_65bad6_idx')],
            },
        ),
    ]
