"""
Django settings for recommendica project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

#: The Django project root — ``backend/`` in this monorepo.  manage.py,
#: db.sqlite3, templates/ and staticfiles/ all live here.
BASE_DIR = Path(__file__).resolve().parent.parent

#: The repository root, one level up from ``backend/``.  Environment files live
#: there because docker compose reads them from the same place
#: (``--env-file .env.production``), so both halves of the monorepo are
#: configured from one file rather than two copies that drift apart.
REPO_ROOT = BASE_DIR.parent


def _env_bool(name: str, default: bool) -> bool:
    """Parse a boolean environment variable."""
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


#: Single source of truth for the mode.  This used to be read twice with two
#: different defaults ("True" when picking the env file, "False" when deciding
#: whether to require DB_* variables), so running with no DEVELOPMENT_MODE set
#: looked for .env.development and then refused to start over missing Postgres
#: credentials.  Production is opt-out: unset means development.
DEVELOPMENT_MODE = _env_bool("DEVELOPMENT_MODE", True)


def load_project_env():
    """
    Load the environment file that matches the current mode.

    Development is the default for local commands. Production is selected
    when DEVELOPMENT_MODE is explicitly false, which is how docker compose
    and the deploy target run.

    Each file is looked for in the repository root first and then in
    ``backend/``.  The root is the canonical location — it is where
    ``docker compose --env-file`` and ``deploy.sh`` read from — but a file kept
    beside manage.py still works for anyone who only ever runs the backend.
    ``load_dotenv`` never overrides a value that is already set, so with both
    present the root wins, and a real environment variable beats both.
    """

    env_file = ".env.development" if DEVELOPMENT_MODE else ".env.production"
    for name in (".env", env_file):
        for directory in (REPO_ROOT, BASE_DIR):
            load_dotenv(directory / name, override=False)


load_project_env()

for env_name in (
    "OPENAI_API_KEY",
    "LANGSMITH_ENDPOINT",
    "LANGSMITH_API_KEY",
    "LANGSMITH_PROJECT",
):
    env_value = os.getenv(env_name)
    if env_value is not None:
        os.environ[env_name] = env_value
    

CHROMA_HOST = os.getenv("RE_CHROMA_HOST", "localhost")
CHROMA_PORT = int(os.getenv("RE_CHROMA_PORT", "5050"))

# When ChromaDB is unreachable the pipeline fails loudly by default.  The old
# behaviour — silently substituting an empty in-memory collection — made a
# misconfigured deployment look healthy while every search returned nothing.
CHROMA_ALLOW_EPHEMERAL_FALLBACK = _env_bool("CHROMA_ALLOW_EPHEMERAL_FALLBACK", False)

# chromadb builds its HTTP session with no timeout at all, so these bound it:
# CHROMA_TIMEOUT caps each request, CHROMA_CONNECT_WAIT caps how long a request
# waits for another thread's client handshake before failing fast.
CHROMA_TIMEOUT = float(os.getenv("CHROMA_TIMEOUT", "30"))
CHROMA_CONNECT_WAIT = float(os.getenv("CHROMA_CONNECT_WAIT", "20"))

os.environ["LANGSMITH_TRACING"] = os.getenv("LANGSMITH_TRACING", "True")

SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")

DEFAULT_LLM_MODEL = os.getenv("DEFAULT_LLM_MODEL", "openai/gpt-oss-120b")

# ── AI / RAG Pipeline Settings ─────────────────────────────────────────────

# Embedding
OLLAMA_EMBEDDING_MODEL = os.getenv("OLLAMA_EMBEDDING_MODEL", "embeddinggemma")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "embeddinggemma")
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "100"))

EMBEDDING_TIMEOUT = int(os.getenv("EMBEDDING_TIMEOUT", "60"))
EMBEDDING_CACHE_MAX_SIZE = int(os.getenv("EMBEDDING_CACHE_MAX_SIZE", "1024"))

# LLM
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0"))

# Per-request HTTP timeout for the LLM provider.  Bound to the client at
# construction time — LangChain silently drops per-call timeouts.
LLM_REQUEST_TIMEOUT = int(os.getenv("LLM_REQUEST_TIMEOUT", "120"))
# Query transforms are short prompts with short answers; they should not be
# allowed to stall for as long as an answer-generation call.
LLM_TRANSFORM_TIMEOUT = int(os.getenv("LLM_TRANSFORM_TIMEOUT", "30"))
LLM_MAX_RETRIES = int(os.getenv("LLM_MAX_RETRIES", "2"))
LLM_CACHE_TTL = int(os.getenv("LLM_CACHE_TTL", "900"))
LLM_CACHE_MAX_SIZE = int(os.getenv("LLM_CACHE_MAX_SIZE", "512"))

# Retrieval
TOP_K = int(os.getenv("TOP_K", "5"))
CANDIDATE_MULTIPLIER = int(os.getenv("CANDIDATE_MULTIPLIER", "4"))
CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "5"))
COLLECTION_NAME = os.getenv("COLLECTION_NAME", "arxiv_embeddings")

# ── Pipeline shape / throughput ─────────────────────────────────────────────
# Query transforms are independent LLM calls and run concurrently; a transform
# that misses VARIANT_STAGE_TIMEOUT is dropped so retrieval degrades instead of
# the request hanging.
ENABLE_HYDE = _env_bool("ENABLE_HYDE", True)
ENABLE_STEP_BACK = _env_bool("ENABLE_STEP_BACK", True)
ENABLE_RAG_FUSION = _env_bool("ENABLE_RAG_FUSION", True)
VARIANT_MAX_WORKERS = int(os.getenv("VARIANT_MAX_WORKERS", "3"))
VARIANT_STAGE_TIMEOUT = float(os.getenv("VARIANT_STAGE_TIMEOUT", "45"))

# Reciprocal Rank Fusion damping constant.
RRF_K = int(os.getenv("RRF_K", "60"))

# Hard cap on documents handed to answer generation.  Answer generation is the
# dominant cost of a request (one LLM call per CHUNK_SIZE documents), so this is
# the main latency dial: 12 docs at CHUNK_SIZE=5 means 3 generation calls, run
# concurrently.  Raising it costs proportionally more time and tokens.
MAX_CONTEXT_DOCS = int(os.getenv("MAX_CONTEXT_DOCS", "12"))

# Per-document character budget inside a generation prompt.
MAX_DOC_CHARS_IN_PROMPT = int(os.getenv("MAX_DOC_CHARS_IN_PROMPT", "1500"))

# How many chunk answers may be generated at once.
GENERATION_MAX_WORKERS = int(os.getenv("GENERATION_MAX_WORKERS", "3"))

# ── Relevance agent ─────────────────────────────────────────────────────────
# Grades every retrieved paper against the query, drops the unrelated ones, and
# — when too few survive — rewrites the query using the rejection reasons and
# searches again. Costs one LLM call per round, and saves generation calls by
# not answering from papers that were never on topic.
ENABLE_RELEVANCE_AGENT = _env_bool("ENABLE_RELEVANCE_AGENT", True)
# Grading needs reliable JSON; point this at a smaller/cheaper model only after
# checking it returns parseable verdict lists (parse failures are logged).
AGENT_MODEL = os.getenv("AGENT_MODEL") or DEFAULT_LLM_MODEL
AGENT_TIMEOUT = int(os.getenv("AGENT_TIMEOUT", "30"))
# Search attempts, including the first: 2 means at most one refined retry.
AGENT_MAX_ITERATIONS = int(os.getenv("AGENT_MAX_ITERATIONS", "2"))
# Related papers needed before the agent stops looking.
AGENT_MIN_RELEVANT_DOCS = int(os.getenv("AGENT_MIN_RELEVANT_DOCS", "3"))
# How many fused candidates get graded per round.
AGENT_GRADE_CANDIDATES = int(os.getenv("AGENT_GRADE_CANDIDATES", "20"))
# Minimum relevance score to keep a paper (0-1). Raise to be stricter.
AGENT_RELEVANCE_THRESHOLD = float(os.getenv("AGENT_RELEVANCE_THRESHOLD", "0.5"))
# Wall-clock budget for the whole loop, independent of the attempt count.
AGENT_DEADLINE = float(os.getenv("AGENT_DEADLINE", "90"))
AGENT_MAX_CANDIDATE_CHARS = int(os.getenv("AGENT_MAX_CANDIDATE_CHARS", "400"))

# ── Live arXiv fallback ─────────────────────────────────────────────────────
# When the indexed collection cannot supply AGENT_MIN_RELEVANT_DOCS related
# papers, the agent searches arxiv.org directly and grades what comes back the
# same way it grades local results. Requires ENABLE_RELEVANCE_AGENT: the grader
# is what holds live results to the same standard, so without it the fallback
# stays off. If arXiv cannot be reached the request is served from ChromaDB
# alone — an unreachable extra never costs the user the local papers.
ENABLE_ARXIV_FALLBACK = _env_bool("ENABLE_ARXIV_FALLBACK", True)
ARXIV_API_URL = os.getenv("ARXIV_API_URL", "https://export.arxiv.org/api/query")
ARXIV_FALLBACK_MAX_RESULTS = int(os.getenv("ARXIV_FALLBACK_MAX_RESULTS", "10"))
ARXIV_FALLBACK_TIMEOUT = float(os.getenv("ARXIV_FALLBACK_TIMEOUT", "15"))
# arXiv asks API clients to leave a gap between requests and to identify
# themselves; both are honoured process-wide.
ARXIV_MIN_REQUEST_INTERVAL = float(os.getenv("ARXIV_MIN_REQUEST_INTERVAL", "3"))
ARXIV_USER_AGENT = os.getenv(
    "ARXIV_USER_AGENT",
    "Recommendica/1.0 (research recommender; +https://recommendica.nevatal.tech)",
)
# Content terms per search. arXiv ANDs them, so more terms means a narrower
# search; past half a dozen it starts excluding the papers it wants.
ARXIV_MAX_QUERY_TERMS = int(os.getenv("ARXIV_MAX_QUERY_TERMS", "6"))
ARXIV_SORT_BY = os.getenv("ARXIV_SORT_BY", "relevance")
ARXIV_BREAKER_THRESHOLD = int(os.getenv("ARXIV_BREAKER_THRESHOLD", "3"))
ARXIV_BREAKER_COOLDOWN = float(os.getenv("ARXIV_BREAKER_COOLDOWN", "300"))

# ── Boundary verification ───────────────────────────────────────────────────
# Query check: one cheap LLM classification before the pipeline spends
# anything, so "hi" does not cost three transforms, a retrieval round trip, a
# grading call and a generation call. Fails open — a checker that is down or
# unparseable lets the query through.
ENABLE_QUERY_VERIFICATION = _env_bool("ENABLE_QUERY_VERIFICATION", True)
QUERY_VERIFICATION_TIMEOUT = int(os.getenv("QUERY_VERIFICATION_TIMEOUT", "15"))
# Only catches what is certainly unusable ("q", "?"); "AI" and "RAG" are
# real topics, so judging meaning is left to the model check.
QUERY_MIN_CHARS = int(os.getenv("QUERY_MIN_CHARS", "2"))
# Upper bound is a prompt-budget guard: the query goes into every transform,
# grading and generation prompt the request makes.
QUERY_MAX_CHARS = int(os.getenv("QUERY_MAX_CHARS", "1000"))

# Result check: a deterministic report on the selected papers (count, sources,
# retrieval confidence, query-term coverage) attached to the response. No LLM
# call, so it is on by default.
ENABLE_RESULT_VERIFICATION = _env_bool("ENABLE_RESULT_VERIFICATION", True)

# Answer grounding: audits each generated answer against its source papers and
# fills the UI's faithfulness score + claim list. OFF by default — it adds one
# LLM call per chunk on the critical path. Relevance filtering above is what
# keeps answers on topic; this measures how well they stick to their sources.
ENABLE_ANSWER_EVALUATION = _env_bool("ENABLE_ANSWER_EVALUATION", False)
ANSWER_EVALUATION_TIMEOUT = int(os.getenv("ANSWER_EVALUATION_TIMEOUT", "45"))

# Deep analysis: complete evidence audit, at most one repair, then re-audit.
# Checks run independently for each chunk; these cap the added provider work.
DEEP_REVIEW_MODEL = os.getenv("DEEP_REVIEW_MODEL") or AGENT_MODEL
DEEP_REVIEW_TIMEOUT = int(os.getenv("DEEP_REVIEW_TIMEOUT", "25"))
DEEP_REPAIR_TIMEOUT = int(os.getenv("DEEP_REPAIR_TIMEOUT", "30"))
DEEP_REVIEW_DEADLINE = float(os.getenv("DEEP_REVIEW_DEADLINE", "90"))

# ── Serving limits ──────────────────────────────────────────────────────────
# Concurrent pipeline runs allowed per process; excess requests get a 503 with
# Retry-After rather than all timing out together.
MAX_CONCURRENT_QUERIES = int(os.getenv("MAX_CONCURRENT_QUERIES", "8"))
SSE_HEARTBEAT_SECONDS = float(os.getenv("SSE_HEARTBEAT_SECONDS", "15"))
READINESS_CACHE_SECONDS = float(os.getenv("READINESS_CACHE_SECONDS", "10"))
# Health checks must answer fast even when a dependency is stalled.
READINESS_TIMEOUT = float(os.getenv("READINESS_TIMEOUT", "10"))
READINESS_PROBE_TIMEOUT = int(os.getenv("READINESS_PROBE_TIMEOUT", "5"))

# Rerank (None = disabled)
RERANK_MODEL = os.getenv("RERANK_MODEL") or None
RERANK_TOP_N = os.getenv("RERANK_TOP_N") or None
RERANK_TIMEOUT = int(os.getenv("RERANK_TIMEOUT", "15"))
# Consecutive rerank failures before the reranker is skipped for a cooldown.
RERANK_BREAKER_THRESHOLD = int(os.getenv("RERANK_BREAKER_THRESHOLD", "3"))
RERANK_BREAKER_COOLDOWN = int(os.getenv("RERANK_BREAKER_COOLDOWN", "300"))

# Query-transform models
HYDE_MODEL = os.getenv("HYDE_MODEL", "mistralai/mistral-nemo")
STEP_BACK_MODEL = os.getenv("STEP_BACK_MODEL","mistralai/mistral-nemo")
RAG_FUSION_MODEL = os.getenv("RAG_FUSION_MODEL", "mistralai/mistral-nemo")
RAG_FUSION_N_VARIANTS = int(os.getenv("RAG_FUSION_N_VARIANTS", "4"))

# Confidence gate
CONFIDENCE_ALPHA = float(os.getenv("CONFIDENCE_ALPHA", "0.5"))
CONFIDENCE_BETA = float(os.getenv("CONFIDENCE_BETA", "0.3"))
CONFIDENCE_GAMMA = float(os.getenv("CONFIDENCE_GAMMA", "0.2"))
CONFIDENCE_THRESHOLD = float(os.getenv("CONFIDENCE_THRESHOLD", "0.75"))


DEBUG = _env_bool("DEBUG", False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,backend,0.0.0.0,recommendica.nevatal.tech"
    ).split(",")
    if host.strip()
]

# ── Donations (Paddle) ───────────────────────────────────────────────────────
# Entirely optional: with no credentials the donate endpoints report themselves
# as disabled and the UI hides the button.  Sandbox and live use different API
# hosts and mutually incompatible keys, so PADDLE_ENVIRONMENT drives both the
# host the server calls and the environment Paddle.js is initialised with.
PADDLE_ENVIRONMENT = os.getenv("PADDLE_ENVIRONMENT", "sandbox")
# Server-side API key (secret — starts with pdl_live_ / pdl_sdbx_).
PADDLE_API_KEY = os.getenv("PADDLE_API_KEY", "")
# Client-side token for Paddle.js (public — it is served to the browser).
PADDLE_CLIENT_TOKEN = os.getenv("PADDLE_CLIENT_TOKEN", "")
# Secret for the notification destination that posts to /donate/webhook/.
PADDLE_WEBHOOK_SECRET = os.getenv("PADDLE_WEBHOOK_SECRET", "")
# The catalogue product donations are billed against; the amount itself is a
# custom price created per checkout, which is what makes them pay-what-you-want.
PADDLE_DONATION_PRODUCT_ID = os.getenv("PADDLE_DONATION_PRODUCT_ID", "")

# First entry is the default. Only currencies your Paddle account supports.
PADDLE_DONATION_CURRENCIES = os.getenv("PADDLE_DONATION_CURRENCIES", "USD,EUR,GBP")
# Suggested amounts, in major units, shown as buttons.
PADDLE_DONATION_PRESETS = os.getenv("PADDLE_DONATION_PRESETS", "5,15,50")
PADDLE_DONATION_MIN_AMOUNT = os.getenv("PADDLE_DONATION_MIN_AMOUNT", "1")
PADDLE_DONATION_MAX_AMOUNT = os.getenv("PADDLE_DONATION_MAX_AMOUNT", "1000")
PADDLE_REQUEST_TIMEOUT = float(os.getenv("PADDLE_REQUEST_TIMEOUT", "15"))
# Replay window for webhook signatures, in seconds. Paddle's own example uses
# 5s, which rejects legitimate retries and anything crossing a skewed clock;
# 0 disables the freshness check and relies on the signature alone.
PADDLE_WEBHOOK_TOLERANCE = int(os.getenv("PADDLE_WEBHOOK_TOLERANCE", "300"))

DEBUG = os.getenv("DEBUG", "False") == "True"



CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173,https://recommendica.nevatal.tech,http://recommendica.nevatal.tech",
    ).split(",")
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://recommendica.nevatal.tech,http://recommendica.nevatal.tech",
    ).split(",")
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "airecommender",
    "corsheaders",
]

REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Applied per view via throttle_scope, not globally: the search endpoints
    # are already bounded by MAX_CONCURRENT_QUERIES, while the donation
    # checkout is unauthenticated and creates a record at Paddle per call.
    'DEFAULT_THROTTLE_RATES': {
        'donation': os.getenv("DONATION_THROTTLE_RATE", "20/hour"),
    },
    # Required for throttling to mean anything behind a proxy.  Left unset,
    # DRF keys the rate limit on the whole X-Forwarded-For header — and nginx
    # *appends* to whatever the client sent, so a caller could mint a fresh
    # bucket per request just by varying the prefix.  With the hop count set,
    # DRF takes the address that many entries from the end: the one nginx
    # added, which the client cannot forge.  Raise it if you add another proxy
    # (a CDN, say) in front of nginx.
    'NUM_PROXIES': int(os.getenv("NUM_PROXIES", "1")),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Research Recommender API',
    'DESCRIPTION': 'Arxiv Research Recommender API with Advanced RAG pipeline',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "recommendica.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "recommendica.wsgi.application"


if not DEVELOPMENT_MODE:
    required_vars = [
        "DB_NAME",
        "DB_USER",
        "DB_PASSWORD",
        "DB_HOST",
    ]

    missing = [var for var in required_vars if not os.getenv(var)]

    if missing:
        raise Exception(
            f"Missing required database environment variables: {', '.join(missing)}"
        )

if DEVELOPMENT_MODE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "db"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Logging ──────────────────────────────────────────────────────────────────
# Log everything to stdout so Docker / docker compose logs captures it.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {name} | {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "airecommender": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}
