"""
Hypothetical Document Embeddings (HyDE) for arxiv paper search.

Flow:
  user query
      → LLM generates a fake arxiv abstract (the "hypothetical doc")
      → embed the fake abstract (instead of raw query)
      → retrieve from ChromaDB using that embedding
      → rerank + return results

Why: raw queries ("faster transformers") are short and vague.
     Hypothetical abstracts look like real papers and land closer
     to actual paper embeddings in vector space.

Paper: Gao et al. 2022 — arXiv:2212.10496
"""

import json
from pipeline.llm_service import OpenRouterService
import chromadb
from chromadb.utils import embedding_functions

# ── clients ────────────────────────────────────────────────────────────────────
llm_service = OpenRouterService()

chroma_client = chromadb.PersistentClient(path="./chroma_db")

embed_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="BAAI/bge-small-en-v1.5"
)

collection = chroma_client.get_or_create_collection(
    name="arxiv_papers",
    embedding_function=embed_fn,
    metadata={
        "hnsw:space": "cosine",
        "hnsw:construction_ef": 200,
        "hnsw:M": 32,
        "hnsw:search_ef": 150,
    },
)

# ── prompts ────────────────────────────────────────────────────────────────────
HYDE_SYSTEM = """You are a researcher writing arxiv paper abstracts.

Given a user's search query, write a single hypothetical arxiv abstract
that would perfectly answer what the user is looking for.

Rules:
- Write ONLY the abstract text, no title, no authors, no preamble
- Match the style and density of real arxiv abstracts
- Include specific technical terms, methods, and results the paper would contain
- Length: 80–150 words
- Do not start with "Abstract:" or any label
"""


# ── core functions ─────────────────────────────────────────────────────────────
def generate_hypothetical_abstract(query: str) -> str:
    """Ask the LLM to write a fake abstract that answers the query."""
    response = llm_service.generate_response(
        prompt=query,
        model="mistralai/mistral-nemo",
        system_instruction_string=HYDE_SYSTEM,
        response_mime_type_param="text/plain"
    )
    return response


def hyde_retrieve(
    query: str,
    top_k: int = 10,
    where: dict | None = None,
) -> dict:
    """
    Full HyDE retrieval pipeline.

    Args:
        query:  raw user query
        top_k:  number of results to return
        where:  optional ChromaDB metadata filter
                e.g. {"categories": {"$contains": "cs.LG"}}

    Returns:
        dict with keys:
            hypothetical_abstract  — what the LLM generated
            results                — list of retrieved papers (id, title, abstract, score)
    """
    # step 1: generate hypothetical abstract
    hypo_abstract = generate_hypothetical_abstract(query)

    # step 2: embed and retrieve using the hypothetical abstract as the query
    query_kwargs = {
        "query_texts": [hypo_abstract],
        "n_results": top_k,
        "include": ["documents", "metadatas", "distances"],
    }
    if where:
        query_kwargs["where"] = where

    raw = collection.query(**query_kwargs)

    # step 3: structure results
    results = []
    for doc_id, doc, meta, dist in zip(
        raw["ids"][0],
        raw["documents"][0],
        raw["metadatas"][0],
        raw["distances"][0],
    ):
        results.append(
            {
                "id": doc_id,
                "title": meta.get("title", ""),
                "abstract": doc,
                "categories": meta.get("categories", ""),
                "year": meta.get("year", ""),
                "cosine_distance": round(dist, 4),
                "similarity": round(1 - dist, 4),
            }
        )

    return {
        "query": query,
        "hypothetical_abstract": hypo_abstract,
        "results": results,
    }


def print_results(output: dict) -> None:
    print(f"\n{'='*70}")
    print(f"Query: {output['query']}")
    print(f"\nHypothetical abstract generated by LLM:")
    print(f"  {output['hypothetical_abstract'][:300]}...")
    print(f"\nTop {len(output['results'])} retrieved papers:")
    for i, r in enumerate(output["results"], 1):
        print(f"\n  [{i}] {r['title']}")
        print(f"       ID: {r['id']}  |  similarity: {r['similarity']}")
        print(f"       Categories: {r['categories']}")
        print(f"       Abstract: {r['abstract'][:120]}...")


# ── example usage ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    queries = [
        "making transformers faster with fewer parameters",
        "detecting objects in images using vision transformers",
        "reinforcement learning from human feedback for language models",
    ]

    for query in queries:
        output = hyde_retrieve(query, top_k=5)
        print_results(output)
        print()